[tox]
envlist = 
	py36
	example{trace}
isolated_build = True

[testenv]
changedir =
	exampletrace: examples/trace
commands =
	py36: python -m unittest
	example{trace}: python -m lure
	example{trace}: python ../../tests/diff_example.py
	example{trace}: python plot.py
