from abc import ABC, abstractmethod
from cgi import test
from enum import Enum
from multiprocessing.sharedctypes import Value
import os
from typing import Any, Dict, List, Set, Tuple, Union, TYPE_CHECKING
from unittest import SkipTest
import numpy as np

from lure.config.configuration import StatsConfig
if TYPE_CHECKING:
    from lure.simulation import Simulation, SimulationResult

import simpy

class StatType(Enum):

    PCLK_EST_TIME = "pclk_est_time"
    CONT_LCL_TIME = "cont_local_time"
    EST_SHARED_TIME = "est_shared_time"
    SUCC_COMM = "succ_comm"
    EST_SHARED_TIME_TM = "est_shared_time_tm"
    CLK_DEAD_PERIOD = "clk_dead_periods"
    PACKETS_SENT_TIME = "packets_sent_time"
    PACKETS_RECEIVED_TIME = "packets_received_time"
    NODE_TOTAL_ROOT_TIMEOUT = "node_total_root_timeout"
    ROOT_TIMEOUT = "root_timeout"


    # Value Stats
    SIMULATION_TIME = "simulation_time"
    NODE_ID = "node_id" # Tracks the node_id of the node 
    NODE_TOTAL_ONTIME = "node_total_ontime" # cumulative on-time 
    NODE_TOTAL_OFFTIME = "node_total_offtime" # cumulative off-time 
    NODE_LIFECYCLE_RATIO = "node_lifecycle_ratio" # lifecycle ratio seen in simulation 
    NODE_LIFECYCLE_RATIO_NOMINAL = "node_lifecycle_ratio_nominal" # lifecycle ratio selected in configuration 
    NODE_TRAFFIC_RATE = "node_traffic_rate" # traffic rate selected in configuration 
    PACKETS_SENT_APP = "packets_sent_app" # the number of packets sent that originated from this node's application layer (does not include packets generated in lower layers)
    PACKETS_RECEIVED_APP = "packets_received_app" # the number of packets that were received by the application layer 
    PACKETS_RECEIVED_NET = "packets_received_net" # the number of packets that were received by the network layer
    PACKETS_SENT_ILL = "packets_sent_ill" # the number of packets successfully sent from the ill layer 
    PACKETS_DROPPED_ILL = "packets_dropped_ill" # the number of packets dropped or discarded from the class ILL and its children 
    PACKETS_GENERATED = "packets_generated" # the number of packets generated by this node
    MAC_ACKS_RECEIVED = "mac_acks_received" # the number of ACK type packets received by the MAC layer 
    MAC_DATA_RECEIVED = "mac_data_received" # the number of DATA type packets received by the MAC layer 
    MAC_CONTROL_RECEIVED = "mac_control_received" # the number of CONTROL type packets received by the MAC layer 
    MAC_DEATHS_DURING_ACK = "mac_deaths_during_ack" # the number of times a node "dies" while sending or waiting on and ACK packet 

    # Time Series Stats
    NODE_RESTART = "node_restart" # (boot time, simulation duration of off-time before boot) 
    NODE_DIE = "node_die" # (sim time the node died, duration of on-time)  
    NODE_OFFTIME = "node_offtime" # (time a node finished booting, duration of off-time+boot) 
    NODE_STATE = "node_state" # time of state change and new state (off, booting, operating, sleeping) 
    LMP_EARLY_DIE = "lmp_early_die" # the time at which at which the node dies by lmp and the duration of its on time 
    LMP_ON_TIME = "lmp_on_time"  # the time at which the lmp's "on time" setting is changed and the value it is changing to 
    PACKETS_IN_QUEUE = "packets_in_queue" # time the queue was update and new total size 
    PACKET_QUEUE_EVENTS = "packet_queue_events" #T he time a packet is removed from the queue and the time the same packet was added to the queue  (remove time, arrival time)
    NETWORK_PACKET_TRAILS = "network_packet_trails" # tracks a packets hops through the network layer in the form (Arrival Time, [Generation Time, [hop_node_id, hop_arrival_timestamp]) 
    NETWORK_BROADCASTS = "network_broadcasts" # when a broadcast packet is received by the network it logs the simulation time of reception, sender_id, and a list of nodes in the sender_id's neighborhood 
    MAC_IS_SENDING = "mac_is_sending" # the time the state changed and a boolean representing whether the mac layer is in sending (states are not necessarily mutually exclusive) 
    MAC_IS_TRANSMITTING = "mac_is_transmitting" # the time the state changed and a boolean representing whether the mac layer is in transmitting (states are not necessarily mutually exclusive) 
    MAC_IS_LISTENING = "mac_is_listening" # the time the state changed and a boolean representing whether the mac layer is in listening (states are not necessarily mutually exclusive) 
    MAC_IS_RECEIVING = "mac_is_receiving" # the time the state changed and a boolean representing whether the mac layer is in receiving (states are not necessarily mutually exclusive) 
    ILL_HANDSHAKE = "ill_handshake" # tracks every time a new handshake has been established by the ILL if one wasn't already establish
    STORAGE_VOLTAGE = "storage_voltage" # the time of a voltage change and the new voltage value
    HARVESTER_CHARGING_POWER = "harvester_charging_power" # Represents the current instantaneous power being harvested in .Logs every time the energy model updates

    # List Stats
    PACKET_ARRIVAL_INTERVALS = "packet_arrival_intervals" # times between packets being generated via the traffic generation process 
    NETWORK_NEIGHBORS = "network_neighbors" # all nodes in the neighborhood of this node 
    PHYSICAL_NEIGHBORS = "physical_neighbors" # the physical neighbors of the node 

    PACKETS_GENERATED_DESTINATIONS = "packets_generated_destinations"

    def __str__(self):
        return self.value

StatName = Union[StatType, str]

class StatsObserver(ABC):
    """An abstract class that observes changes in stats
    """
    @abstractmethod
    def on_update(self, name: StatName, val_change: Union[int, float], stats: 'Stats'):
        """When this method is called any subclass it tracks a changed stat and may take some action. For example, see :py:meth:`lure.simulation.Simulation.on_update`

        :param name: The key to the stats dictionary item
        :type name: StatName
        :param val_change: The change in value of the stat
        :type val_change: Union[int, float]
        :param stats: The stats object being observed
        :type stats: Stats
        """
        pass

class StatLevel(Enum):
    VERBOSE = "verbose"
    NORMAL = "normal"
    QUIET = "quiet"
    SILENT = "silent"

    def __ge__(self, other):
        l = ["verbose", "normal", "quiet", "silent"]
        return l.index(self.value) >= l.index(other.value)

    def __str__(self):
        return self.name

class Stats:

    def __init__(self, config: StatsConfig, label: str):
        self.stats_dict: Dict[Any, Any] = dict()
        self.time_series_dict: Dict[Any, List[Tuple[int, Any]]] = dict()
        self.list_dict: Dict[Any, List[Any]] = dict()
        self.observers: Set[StatsObserver] = set()
        self.label = label
        self.simpy_env: simpy.core.Environment = None

        self.level: StatLevel = StatLevel(config.config["level"])
        self.default_level: StatLevel = StatLevel(config.config["default"])
        self.stat_levels: Dict[StatType, StatLevel] = { StatType(k): StatLevel(v) for k, v in config.config["stats"].items() }

    def initialize(self, sim: 'Simulation'):
        """Initialize with the start of the simulation

        :param sim: The simulation this Stats object is a part of
        :type sim: Simulation
        """
        self.simpy_env = sim.simpy_env

    def _record_stat(self, name: StatName) -> bool:
        """Checks to see if a stat should be recorded based upon the stat configurations.  

        :param name: The stat to check the level of
        :type name: StatName
        :return: True if the stat's configured collection level is greater than or equal to the simulation :py:class:`lure.node.stats.StatLevel`. If the "name" parameter does not exist in the configuration. \
            Then it is assigned the default level.
        :rtype: bool
        """
        try:
            stat_level = self.stat_levels[name]
        except KeyError:
            stat_level = self.default_level
        if stat_level >= self.level:
            return True
        return False

    def register(self, name: StatName, initial_val: Any = 0):
        """Adds an item to the stats dictionary that is keyed by "name" and assigned "initial_val" as its value. Used for "Value" stats\
        You can register a stat that does not already exist in StatName and it will be assigned the default collection level in :py:class:`lure.node.stats.StatLevel`

        :param name: The key to the new stat dictionary item
        :type name: StatName
        :param initial_val: Initial value to give to the dictionary item, defaults to 0
        :type initial_val: Any, optional
        """
        if not self._record_stat(name):
            return

        if str(name) in self.stats_dict:
            print(f'Warning: stat {name} already registered.')
        self.stats_dict[str(name)] = initial_val

    def register_time_series(self, name: StatName):
        """Adds an item to the stats dictionary that is keyed by "name" and assigned an empty list as its initial value. Used for "Time Series" stats\
        You can register a stat that does not already exist in StatName and it will be assigned the default collection level in :py:class:`lure.node.stats.StatLevel`

        :param name: The key to the new stat dictionary item
        :type name: StatName
        """
        if not self._record_stat(name):
            return

        if str(name) in self.time_series_dict:
            print(f'Warning: time series {name} already registered.')
        self.time_series_dict[str(name)] = []
    
    def register_list(self, name: StatName):
        """Adds an item to the stats dictionary that is keyed by "name" and assigned an empty list as its initial value. Used for "List" stats\
        You can register a stat that does not already exist in StatName and it will be assigned the default collection level in :py:class:`lure.node.stats.StatLevel`

        :param name: The key to the new stat dictionary item
        :type name: StatName
        """
        if not self._record_stat(name):
            return
        self.list_dict[str(name)] = []

    def get(self, name: StatName, default=None) -> Any:
        """Retrieves a value from the stats dictionary. Used for "Value" stats

        :param name: The key to the value being retrieved
        :type name: StatName
        :param default: The default value returned if the keyed item does not exist, defaults to None
        :type default: Any, optional
        :return: The value of the keyed stat dictionary item
        :rtype: Any
        """
        try:
            return self.stats_dict[str(name)]
        except KeyError:
            return default
    
    def get_time_series(self, name: StatName) -> List[Tuple[int, Any]]:
        """Retrieves a value from the stats dictionary. Used for "Time Series" stats

        :param name: The key to the value being retrieved
        :type name: StatName
        :return: The value of the keyed stat dictionary item
        :rtype: List[Tuple[int, Any]]
        """
        try:
            return self.time_series_dict[str(name)]
        except KeyError:
            return None

    def get_list(self, name: StatName) -> List[Any]:
        """Retrieves a value from the stats dictionary. Used for "List" stats


        :param name: The key to the value being retrieved
        :type name: StatName
        :return: The value of the keyed stat dictionary item 
        :rtype: List[Any]
        """
        try:
            return self.list_dict[str(name)]
        except KeyError:
            return None

    def get_time_series_x_y(self, name: StatName) -> Tuple[List[int], List[Any]]:
        """A variation of :py:meth:`lure.node.stats.Stats.get_time_series` designed to return the time series in a different structure that is more \
        convenient to separate the collected time stamps and data

        :param name: The key to the value being retrieved
        :type name: StatName
        :return: The value of the keyed stat dictionary item
        :rtype: Tuple[List[int], List[Any]]
        """
        ts = self.get_time_series(name)
        if ts is not None:
            return [x[0] for x in ts], [x[1] for x in ts]
        return None, None

    def set(self, name: StatName, val: Any):
        """Set a "Value" stat dictionary item to "val" and register the stat if it has not already been registered. Reports the change in value to any :py:class:`lure.node.stats.StatsObserver`.

        :param name: The key to the stats dictionary item
        :type name: StatName
        :param val: The new value that the stat is being set to
        :type val: Any
        """
        if not self._record_stat(name):
            return

        prev_val = self.get(name, 0)
        try:
            self.stats_dict[str(name)] = val
        except KeyError:
            self.register(name, initial_val=val)

        try:
            val_change = val - prev_val
        except TypeError:
            val_change = None

        for o in self.observers:
            o.on_update(name, val_change, self)

    def update(self, name: StatName, delta: Any):
        """Calls :py:meth:`lure.node.stats.Stats.set` to update a particular "Value" stat by delta

        :param name: The key to the stats dictionary item
        :type name: StatName
        :param delta: The change in value to the stat.
        :type delta: Any
        """
        if not self._record_stat(name):
            return

        try:
            self.set(name, self.get(name, 0) + delta)
        except TypeError:
            print(f'Error: cannot update stat {name} with delta {delta}.')

    def increment(self, name: StatName):
        """Calls :py:meth:`lure.node.stats.Stats.set` to increase a particular "Value" stat by 1

        :param name: The key to the stats dictionary item
        :type name: StatName
        """
        if not self._record_stat(name):
            return

        val = self.get(name, 0)

        try:
            val += 1
            self.set(name, val)
        except TypeError:
            print(f'Error: cannot increment stat {name} with value {val}.')

    def decrement(self, name: StatName):
        """Calls :py:meth:`lure.node.stats.Stats.set` to decrease a particular "Value" stat by 1

        :param name: The key to the stats dictionary item
        :type name: StatName
        """
        if not self._record_stat(name):
            return

        val = self.get(name, 0)

        try:
            val -= 1
            self.set(name, val)
        except TypeError:
            print(f'Error: cannot decrement stat {name} with value {val}.')

    def time_series_append(self, name: StatName, val: Any):
        """Adds a new element to a "Time Series" stat. Each element is a Tuple of the form (current_simulation_time, val). \
              Registers the stat if it has not already been registered.

        :param name: The key to the stats dictionary item
        :type name: StatName
        :param val: Any value that is desired to be recorded with a timestamp
        :type val: Any
        """
        if not self._record_stat(name):
            return
        
        ts = self.get_time_series(name)
        if ts is None:
            self.register_time_series(name)
            ts = self.get_time_series(name)
        
        if self.simpy_env:
            ts.append((self.simpy_env.now, val))
        else:
            ts.append((0, val))
    
    def list_append(self, name: StatName, val: Any):
        """Appends a new element "val" to a "List" stat. Registers the stat is it has not already been registered.

        :param name: The key to the stats dictionary item
        :type name: StatName
        :param val: Any value to be placed into the stat
        :type val: Any
        """
        if not self._record_stat(name):
            return
        
        list = self.get_list(name)
        if list is None:
            self.register_list(name)
            list = self.get_list(name)
        
        list.append(val)

    def add_observer(self, obj: StatsObserver):
        """Adds subclass of :py:class:`lure.node.stats.StatsObserver` to the known observers of this stat object

        :param obj: An object that is a subclass of StatsObserver
        :type obj: StatsObserver
        """
        self.observers.add(obj)

    def remove_observer(self, obj: StatsObserver):
        """Removes an observer from the known observers list

        :param obj: An object that is a subclass of StatsObserver
        :type obj: StatsObserver
        """
        self.observers.remove(obj)

    def pretty(self) -> List[str]:
        """Presents the stats dictionary in a human readable format

        :return: Lines to be displayed or written to a file 
        :rtype: List[str]
        """
        lines = []
        for k, v in self.stats_dict.items():
            lines.append(f'{k}:{v}\n')
        lines.sort()

        ts_lines = []
        for k, v in self.time_series_dict.items():
            ts_lines.append(f'{k}:{v}\n')
        ts_lines.sort()

        list_lines = []
        for k, v in self.list_dict.items():
            list_lines.append(f'{k}:{v}\n')
        list_lines.sort()

        lines.extend(ts_lines)
        lines.extend(list_lines)

        return lines

    def close(self, output_dir: str):
        """Closes this Stat object and prints its collected information in human readable format to a file in the output directory

        :param output_dir: The directory to print this objects information to
        :type output_dir: str
        """
        self.simpy_env = None
        self.observers = None

        with open(f'{output_dir}/stats_{self.label}.txt', 'w') as f:
            f.writelines(self.pretty())

    def intersection_diff(self, other: 'Stats') -> Tuple[List[StatName], List[StatName]]:
        diff_names = []
        diff_names_ts = []
        diff_names_list = []
        for k, v in self.stats_dict.items():
            if k in other.stats_dict and other.stats_dict[k] != v:
                diff_names.append(k)
        for k, ts in self.time_series_dict.items():
            if k in other.time_series_dict and other.time_series_dict[k] != ts:
                diff_names_ts.append(k)
        for k, v in self.list_dict.items():
            if k in other.list_dict and other.list_dict[k] != v:
                diff_names_list.append(k)
        return diff_names, diff_names_ts

class StatsProvider:
    """Inherited by classes that will provide statistic information to :py:class:`lure.node.stats.Stats`. Contains a property for stats that is \
        called by :py:class:`lure.node.sensor_node.SensorNode` and cascades down it's submodules. Defines a setter and getter that links the stats \
        properties of all submodules together. Therefore, only one Stats object is created for each simulated node.
    """
    def __init__(self):
        self._stats = None

    @property
    def stats(self):
        try:
            return self._stats
        except:
            return None

    @stats.setter
    def stats(self, stats: Stats):
        self._stats = stats

class StatsParser:
    """This class contains methods that uses raw data collected by Stats to synthesize useful metrics
    """

    @staticmethod
    def single_hop_delays(stats: Stats) -> List[Tuple[int, int]]:
        """How long each packet remained in the queue before it was removed

        :param stats: The stats object the data is pulled from
        :type stats: Stats
        :return: A list of tuples containing (the duration the packet was in the queue, when it was removed)
        :rtype: List[Tuple[int, int]]
        """
        delays = []     # delay = (time for first count sent - time for first pkt to enter queue)
        times = stats.get_time_series(StatType.PACKET_QUEUE_EVENTS)
        for t in range(len(times)):
            if times[t][1] is None:
                continue
            arrival_time = times[t][1]
            removal_time = times[t][0]
            delay_point = removal_time - arrival_time
            delays.append((delay_point, removal_time))
        return delays

    @staticmethod
    def on_off_record(stats: Stats) -> List[Tuple[int, int]]:
        """Creates a record of on and off times. Should only be used after a simulation is complete.

        :param stats: The stats object the data is pulled from
        :type stats: Stats
        :return: A list of on_times indicated by tuples showing (when the node restarted, when the node died)
        :rtype: List[Tuple[int, int]]
        """
        on, _ = stats.get_time_series_x_y(StatType.NODE_RESTART)
        off = stats.get_time_series_x_y(StatType.NODE_DIE)
        return list(zip(on, off))

    @staticmethod
    def single_hop_active_delays(stats: Stats) -> List[Tuple[int, int]]:  
        """How long each packet remained in the queue before it was removed, but removing any delay due to off-time 

        :param stats: The stats object the data is pulled from
        :type stats: Stats
        :return: A list where each element is (the active delay, removal time)
        :rtype: List[Tuple[int, int]]
        """
        delays = []     # delay = sum of on times between time for packet arrived and packet sent        
        times = stats.get_time_series(StatType.PACKET_QUEUE_EVENTS)

        for t in range(len(times)):
            if type(times[t][1]) != int:
                continue
            arrival_time = times[t][1]
            removal_time = times[t][0]
            sum_offtime = StatsParser.total_offtime(stats, stop=removal_time, start=arrival_time)
            active_delay_point = removal_time - arrival_time - sum_offtime
            delays.append((active_delay_point, removal_time))
        return delays

    @staticmethod
    def inter_handshake_intervals(stats: Stats) -> List[Tuple[int, int]]:
        """Retrieves the durations between handshake events

        :param stats: The stats object the data is pulled from
        :type stats: Stats
        :return: A list of events in the form (time since the last handshake, handshake timestamp)
        :rtype: List[Tuple[int, int]]
        """
        ihis = []

        handshake_times, _ = stats.get_time_series_x_y(StatType.ILL_HANDSHAKE)

        for i, t in enumerate(handshake_times[1:]):
            ihis.append((t - handshake_times[i], t))

        return ihis

    @staticmethod
    def time_to_handshakes(stats_list: List[Stats]) -> List[Tuple[int, int]]:
        """This is an experimental function that needs to be verified for accuracy. It is intended to show how long a node tries to  \
        send a packet before a handshake is completed.
        """
        tths = []

        ihis = StatsParser.inter_handshake_intervals(stats_list[0])
        queue_sizes = [s.get_time_series(StatType.PACKETS_IN_QUEUE) for s in stats_list]

        # For each IHI, we want to know how long some node was TRYING to send. If multiple
        # nodes were trying to send, we take the max.
        t_prev = 0
        queue_size_indexes = [0] * len(queue_sizes)
        for ihi in ihis:
            t = ihi[1]
            #print(f'ihi {t}')
            max_trying = 0
            for q, (queue_size_index, queue_size_ts) in enumerate(zip(queue_size_indexes, queue_sizes)):
                # Find the first non-zero entry after a zero entry between t_prev and t
                zero_found = False
                for i, (queue_time, queue_size) in enumerate(queue_size_ts[queue_size_index:]):
                    #print(i, queue_time, queue_size, zero_found)
                    if queue_time >= t:
                        queue_size_indexes[q] += i - 1
                        break
                    if queue_size == 0:
                        zero_found = True
                        continue
                    if queue_time < t_prev:
                        # We don't count the zero if it wasn't in the IHI or the last entry before the IHI
                        if queue_size > 0:
                            zero_found = False
                        continue
                    if zero_found:
                        if t - queue_time > max_trying:
                            max_trying = t - queue_time
                        queue_size_indexes[q] += i - 1
                        break

                # If we didn't find a zero, that means the node was trying this whole IHI
                if not zero_found:
                    #print('No zero...')
                    max_trying = t - t_prev

            t_prev = t

            tths.append((max_trying, t))
            # if len(tths) > 20:
            #     print(f'IHI: {ihi[0]} at {t}')
            #     print(f'TTH: {max_trying} at {t}')
            #     print(queue_sizes[0])
            #     print(queue_sizes[1])
            #     exit(0)
        #for tth, ihi in zip(tths, ihis):
        #    print(tth, ihi)
        return tths

    @staticmethod
    def node_throughput_bps(stats: Stats) -> float:
        """Calculates a node's cumulative throughput in bps

        :param stats: The stats object the data is pulled from
        :type stats: Stats
        :return: Cumulative throughput in bits per second
        :rtype: float
        """
        packets_sent = stats.get(StatType.PACKETS_SENT_APP, 0)
        sim_time_ms = stats.get(StatType.SIMULATION_TIME)
        # TODO: node should track bytes sent as well
        bytes_sent = packets_sent * 32
        return bytes_sent * 1000.0 / sim_time_ms

    @staticmethod
    def total_throughput_bps(stats_list: 'SimulationResult') -> float:
        """System-wide cumulative throughput in bps 

        :param stats_list: The stats object the data is pulled from
        :type stats_list: SimulationResult
        :return: System-wide cumulative throughput in bits per second 
        :rtype: float
        """
        return sum([StatsParser.node_throughput_bps(s) for s in stats_list])

    @staticmethod
    def total_steady_throughput_bps(stats_list: 'SimulationResult', skips_for_stabilization=0) -> float:
        """Used to show system-wide cumulative throughput after a certain number of sent packets to evaluate the system in a more stable state

        :param stats_list: The stats object the data is pulled from
        :type stats_list: SimulationResult
        :param skips_for_stabilization: The number of sent packets before you consider the system to be stable, defaults to 0
        :type skips_for_stabilization: int, optional
        :raises ValueError: Prevents skips from being less than 1 or greater than the total packets sent 
        :return: System-wide, cumulative, and steady state throughput
        :rtype: float
        """
        node_send_times = []
        for s in range(len(stats_list)):
            node_send_times.append(StatsParser.get_send_events(stats_list[s]))
        combined_send_times = StatsParser.combine_node_data(node_send_times, node_send_times)
                                
        if skips_for_stabilization < 1:
            raise ValueError("skips must be greater than 0")

        if skips_for_stabilization >= len(combined_send_times):
            raise ValueError('asked for more skips than packets sent')

        num_pkts_sent = len(combined_send_times) - skips_for_stabilization
        simulated_time = combined_send_times[-1] - combined_send_times[skips_for_stabilization-1]
        
        bytes_sent = num_pkts_sent * 32
        throughput = bytes_sent * 1000.0 / simulated_time

        return throughput

    # TODO: Remove this because it is a duplicate function
    @staticmethod
    def get_send_events(stats: Stats) -> List[int]:
        """Retrieves all send times

        :param stats: The stats object the data is pulled from
        :type stats: Stats
        :return: A list of all times a packet was removed from the queue
        :rtype: List[int]
        """
        send_events, rec_events = stats.get_time_series_x_y(StatType.PACKET_QUEUE_EVENTS)
        return send_events

    @staticmethod
    def combine_node_data(sim_data: List[any], sim_times=List[any]) -> List[any]:
        """Combines the data of a number of nodes into one list. This discards any timestamping

        :param sim_data: A list of simulation data where each element should be a node's data
        :type sim_data: List[any]
        :param sim_times: A list of simulation time where each element should be a node's data, defaults to List[any]
        :type sim_times: List[any], optional
        :return: A single list of combined data without timestamping information
        :rtype: List[any]
        """
        combined_data = [] # node0 and node1 combined: array of [time, cummulative pkt count at this time]
        
        num_sim_data = 0
        sim_data_indices = []
        for node in range(len(sim_data)):
            sim_data_indices.append(0)
            num_sim_data += len(sim_data[node])
        
        for i in range(num_sim_data):
            min_time = np.inf
            for node in range(len(sim_data)):
                if (sim_data_indices[node] < len(sim_data[node])) and (sim_times[node][sim_data_indices[node]] < min_time):
                    min_time = sim_times[node][sim_data_indices[node]]
                    node_used = node
            combined_data.append(sim_data[node_used][sim_data_indices[node_used]])
            sim_data_indices[node_used] += 1
            
        return combined_data
